Adjusted api create refund request examples to reflect proper usage o…
taxjar/taxjar-api-docs pull request #95
Opened 2021-05-02 20:45 UTC by atgehrhardt

…f the transactions_reference_id for cURL, Ruby, Node, and Go. They currently match the transaction_id which should not be the case.

2021-05-03 22:22 UTC, cas27 approved these changes

2021-05-04 22:43 UTC, fastdivision approved these changes

2021-05-04 22:47 UTC, fastdivision requested changes
@atgehrhardt I noticed a `123` transaction ID for the Golang `CreateRefund` example. Can you update that as well?

2021-05-10 20:33 UTC, fastdivision approved these changes

2021-05-10 20:34 UTC, merged